### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.ultorg.util.TNEString.toString()" because "<parameter2>" is null

### ISSUE THREAD

**Issue by malcook** [ultorg/public_issues#27]
sqlite database trying to explore a `view` results in error:

![image](https://user-images.githubusercontent.com/484282/169403242-4713a9f3-72a6-457a-8136-0ec9d76ccec9.png)

clicking on `Show and Report Problem` presents its own problem:

![image](https://user-images.githubusercontent.com/484282/169403390-1a0d2068-2b22-4aac-a518-854b6535734e.png)

java.lang.NullPointerException: Cannot invoke "com.ultorg.util.TNEString.toString()" because "<parameter2>" is null
	at com.ultorg.database.dialect.SQLiteBackendDialect.getStorageType(SourceFile:92)
	at com.ultorg.database.SQLConnection.a(SourceFile:3111)
	at com.ultorg.database.SQLConnection.getTableInfo(SourceFile:785)
	at com.ultorg.project.model.m$2.run(SourceFile:1130)
	at com.ultorg.project.e.a(SourceFile:192)
	at com.ultorg.project.e.runTask(SourceFile:130)
	at com.ultorg.project.model.m.populatePrimaryViewTemplate(SourceFile:122)
	at com.ultorg.database.DataSourceAccessor.createPrimaryViewTemplate(SourceFile:114)
	at com.ultorg.project.c.a(SourceFile:406)
	at com.ultorg.project.c.a(SourceFile:257)
	at com.ultorg.project.i.a(SourceFile:503)
	at com.ultorg.project.i$a.b(SourceFile:1127)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

log file is attached:
[messages.log](https://github.com/ultorg/public_issues/files/8734187/messages.log)

**Comment by eirikbakke** [comment]
Thanks for the report! I found the immediate problem and fixed it for the next Ultorg version.

(This error was triggered by a column that does not have a particular declared data type. There is still the question of what to do wrt. formula functions and so on for mixed-type SQLite columns, but that's another issue for the future.)

**Comment by eirikbakke** [comment]
This issue is now fixed in [Ultorg 1.0.8](https://www.ultorg.com/releasenotes/), which was just released. Existing beta users can find the new Ultorg version at the old download link.
