### ISSUE TITLE
Support Redshift

### ISSUE THREAD

**Issue by atroche** [ultorg/public_issues#30]
While technically you can connect to Redshift using the Postgres JDBC driver and run queries, introspection-related features (like those used in DataGrip and Ultorg) fail.

Any idea how long it might be before we can explore our Redshift DB using Ultorg? Thanks!

**Comment by eirikbakke** [comment]
Hi, @atroche! In Ultorg, did you manage to run any queries at all on Redshift? Which features are you referring to as "introspection-related"?

**Comment by atroche** [comment]
hi @eirikbakke , no I didn't! I get errors on connection.

```
INFO [com.ultorg.project.e]: Running SQLTask 'Retrieve table list'
INFO [com.ultorg.database.SQLConnection]: Retrieving table list for catalog 'dev'
INFO [org.netbeans.modules.db.explorer.node.ConnectionNode]: Failed to update properties of ConnectionNode 'PostgreSQL REDACTED:5439/REDACTED (REDACTED)'
org.postgresql.util.PSQLException: Unable to determine a value for MaxIndexKeys due to missing system catalog data.
	at org.postgresql.jdbc.PgDatabaseMetaData.getMaxIndexKeys(PgDatabaseMetaData.java:69)
	at org.postgresql.jdbc.PgDatabaseMetaData.getMaxColumnsInIndex(PgDatabaseMetaData.java:867)
	at org.netbeans.lib.ddl.adaptors.DefaultAdaptor.getMaxColumnsInIndex(DefaultAdaptor.java:2620)
[catch] at org.netbeans.modules.db.explorer.node.ConnectionNode.updateLocalProperties(ConnectionNode.java:317)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.access$200(ConnectionNode.java:65)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:382)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
INFO [com.ultorg.database.SQLConnection]: Can't retrieve table list for catalog dev; skipping (possibly a normal permissions issue)
org.postgresql.util.PSQLException: ERROR: type "e" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:243)
	at org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1343)
	at com.ultorg.database.SQLConnection.a(SourceFile:465)
[catch] at com.ultorg.database.SQLConnection.getDatabasesAndTables(SourceFile:579)
	at com.ultorg.project.model.m$1.run(SourceFile:1088)
	at com.ultorg.project.e.a(SourceFile:191)
	at com.ultorg.project.e.runTask(SourceFile:130)
	at com.ultorg.project.model.m.getTableList(SourceFile:83)
	at com.ultorg.project.c.b(SourceFile:483)
	at com.ultorg.project.c.c(SourceFile:462)
	at com.ultorg.project.i.a(SourceFile:503)
	at com.ultorg.project.i$a.b(SourceFile:1127)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by eirikbakke** [comment]
Ah, I see! Yes, as you say, this is probably an issue that happens when using the PostgreSQL JDBC driver instead of the official Redshift JDBC driver.

For testing purposes, you can try installing Redshift's official JDBC driver in Ultorg as follows:
1) Download the [JDBC 4.2–compatible driver version 2.1 and AWS SDK driver–dependent libraries](https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/2.1.0.9/redshift-jdbc42-2.1.0.9.zip) from [this page](https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-download-driver.html)
2) Extract the ZIP to a folder somewhere (in a location that won't change later).
3) In Ultorg, click the "Internals" menu, then "Services".
4) In the "Services" tab that pops up to the left of the screen, expand "Databases", then right-click "Drivers" and select "New Driver...".
5) Click "Add" and select all of the JAR files that were extracted in step (2). (On Windows, you can select multiple files in the file chooser by holding down shift.)
6) Leave the "Driver Class" name as detected (com.amazon.redshift.jdbc.Driver). There's another class name mentioned on one of the documentation pages, but this one seems to be the right one to use here. Click OK.
7) Now go back to the "Folders" tab, click "Add Data Source", and click "Connect to Database". There should be an "Amazon Redshift" option in the "Driver" dropdown now. Make sure Amazon Redshift is selected, and click "Next".
8) In the next screen, select either "Amazon Redshift (User Name)" or "Amazon Redshift (IAM)" to get Ultorg to show you an example JDBC URL to use.
9) Enter the relevant connection settings and click "Finish".

I'd be curious to hear if this works! One day I will sit down and make Redshift support official, but it will require me to set up a Redshift cluster of my own for testing...
